version: "3.8"

services:
  backend:
    build: ./backend
    container_name: "uecs_navi_creator_backend"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: "uecs_navi_creator_frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend

  db:
    image: mysql:8.2
    container_name: "uecs_navi_creator_db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
