"""recreated databases

Revision ID: 315a632aabde
Revises: 
Create Date: 2023-12-26 03:35:24.395484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315a632aabde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'BlockA',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('uecsid', sa.LargeBinary(6)),
        sa.Column('macaddr', sa.LargeBinary(6)),
        sa.Column('fix_dhcp_flag', sa.LargeBinary(1)),
        sa.Column('fixed_ipaddress', sa.LargeBinary(4)),
        sa.Column('fixed_netmask', sa.LargeBinary(4)),
        sa.Column('fixed_defgw', sa.LargeBinary(4)),
        sa.Column('fixed_dns', sa.LargeBinary(4)),
        sa.Column('vender_name', sa.String(16)),
        sa.Column('node_name', sa.String(16))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BlockA')
    op.drop_table('BlockBItem')
    op.drop_table('BlockB')
    op.drop_table('BlockC')
    op.drop_table('BlockDItem')
    op.drop_table('BlockD')
    # pass
    # ### end Alembic commands ###
