"""recreated databases

Revision ID: a3b5f9c6ab1a
Revises: a1666b2ee5be
Create Date: 2023-12-21 05:19:33.142654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3b5f9c6ab1a'
down_revision: Union[str, None] = 'a1666b2ee5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uecs')
    op.drop_table('parameters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('uecs_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('room', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start', mysql.TIME(), nullable=True),
    sa.Column('end', mysql.TIME(), nullable=True),
    sa.Column('duration', mysql.DATETIME(), nullable=True),
    sa.Column('interval', mysql.DATETIME(), nullable=True),
    sa.Column('ipaddress', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uecs_id'], ['uecs.id'], name='parameters_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('uecs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('node_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('model_number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('vender_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uecs_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mac_address', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
