"""create_blockb_table

Revision ID: f9f667ef8b4f
Revises: 3b4e34a8dabe
Create Date: 2024-01-25 05:38:37.140279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f9f667ef8b4f'
down_revision: Union[str, None] = '3b4e34a8dabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_b',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_a_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('room', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.BLOB(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('lv', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cast', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('sr', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ccm_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('sthr', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stmn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edhr', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edmn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inmn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dumn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rly_l', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rly_h', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_a_id'], ['block_a.uecsid'], name='block_b_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('block_c',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_a_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('room', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.BLOB(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('lv', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cast', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('sr', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ccm_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('sthr', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stmn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edhr', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edmn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inmn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dumn', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rly_l', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rly_h', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_a_id'], ['block_a.uecsid'], name='block_c_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('block_a',
    sa.Column('uecsid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('macaddr', mysql.TINYBLOB(), nullable=True),
    sa.Column('fix_dhcp_flag', mysql.TINYBLOB(), nullable=True),
    sa.Column('fixed_ipaddress', mysql.TINYBLOB(), nullable=True),
    sa.Column('fixed_netmask', mysql.TINYBLOB(), nullable=True),
    sa.Column('fixed_defgw', mysql.TINYBLOB(), nullable=True),
    sa.Column('fixed_dns', mysql.TINYBLOB(), nullable=True),
    sa.Column('vender_name', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('node_name', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('uecsid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('block_d',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_a_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valid', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('room', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.BLOB(), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('ccm_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('cmpope', sa.BLOB(), nullable=True),
    sa.Column('fval', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['block_a_id'], ['block_a.uecsid'], name='block_d_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('block_d')
    op.drop_table('block_a')
    op.drop_table('block_c')
    op.drop_table('block_b')
    # ### end Alembic commands ###
